# Project identity
sonar.projectKey=ApplyUniNow
sonar.projectName=ApplyUniNow
sonar.projectVersion=1.0

# SonarQube server
sonar.host.url=http://3.110.217.88:9000/

# Authentication (use USER token)
sonar.login=sqp_1f1231f855a26a0e475580843fa20267abb81344

# Source code locations
3.110.217.88sonar.sources=components,pages,src,front,server

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude generated / unwanted files
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/public/**

# JavaScript / TypeScript analysis
sonar.language=js

