import React from 'react'
import TopStrip from './TopStrip'

const RefundPolicy = () => {
  const topString = 'Refund Policy';
  return (
    <div className='test-pref-details'>
      <TopStrip topInfoText={topString} goBackStatus={false} />
      <div className='static__container container xsmall-width'>
        <p>Welcome to ApplyUniNow’s refund policy,</p>
        <p>Our client agreements are founded upon the pillars of trustworthiness, sincerity, and security. Each option is meticulously outlined in explicit detail. Our terms are transparent, and there are no concealed provisions.</p>

        <p>The client concurs and acknowledges that the company does not recommend or compel any service or product. The decision to recommend or endorse a specific service or product is solely the client’s and cannot be construed as a company endorsement.</p>

        <p>ApplyUniNow markets all its products and educates all its clients about the opportunities without any external pressure to make a decision on this service or product.</p>

        <p>ApplyUniNow is not affiliated with any government authority, organization, or embassy. As a private limited company, we do not speak or commit or assure on behalf of the authority to grant permits in any ways or forms. Our primary function is to provide assistance, guidance, and advice to individuals seeking to migrate or travel to their preferred country or destination overseas. It is essential to recognize that the final decision regarding all requests rests with the relevant government departments in their respective countries.</p>

        <p>ApplyUniNow will not, under any circumstances, issue refunds for early service withdrawal.</p>
        <p>The refund percentages provided are applicable only to the full-service fee paid, not to the total amount paid. Eligibility for the refund percentage requires the complete payment of the product’s full-service fee without any outstanding balance. Clients may not be eligible for the refund percentage even if they meet one of the specified clauses or have not paid the full-service fee mentioned.</p>

        <p>The services / Immigration pronouncements are sometimes discounted based on future expectations. Clients are registered in advance, before the actual qualification is announced, to ensure that the cap system is met. It is pre-agreed that the client acknowledges this and is prepared to do so to avoid last-minute rushes and prepare accordingly as per all requirements announced by the immigration authorities. If the client’s profile is not eligible after the announcement, the client can choose to transfer to other opportunities.</p>

        <p>ApplyUniNow strictly adheres to a zero-tolerance policy regarding chargebacks. Any customer who disputes a valid credit card payment will be permanently barred from utilizing our services. Consequently, any past-due fees and associated costs will be transferred to collections agencies. Should our collection efforts prove unsuccessful, unpaid debts will be reported to all applicable Credit Reporting Agencies.</p>

        <p>The client acknowledges and concurs that the total invoice amount (bill value) encompasses the ApplyUniNow consultation fee and the applicable tax. Nevertheless, the refund will be calculated solely on the ApplyUniNow consultation fee. The tax component is non-refundable at any juncture.</p>

        <p>In the event of rejection by Visa Officers or Immigration Authorities, including both customary and unusual circumstances, ApplyUniNow will process a refund of the applicable amount, as outlined in the agreed terms. The refund amount will be calculated based on the assistance provided, including the number of working hours involved, and then reviewed considering individual circumstances. If the refund is deemed genuine, it will be processed within 30 working days following receipt of an acknowledgment email from the client to support@applyuninow.com. To facilitate the refund process, the client is required to submit a copy of the rejection letter from the Authority. Failure to provide a copy of the rejection letter or rejection stamp on the client’s passport will prevent ApplyUniNow from processing the refund.</p>
        <p>ApplyUniNow is not liable for any delays caused by third-party services, including authorized service providers. Furthermore, clients are not entitled to a refund of service charges.</p>

        <p>ApplyUniNow is not liable for refunds of any fees or other charges paid to Assessing Bodies, Immigration Authorities, Embassies, Consulates, or High Commissions in the event of a client’s immigration application not being approved. This includes rejection or non-acceptance of a request at any stage by any respective authority. The fees cover the services rendered by ApplyUniNow and do not include assessment fees or any requests made to the client. The client acknowledges and agrees to pay the entire additional fees, as applicable.</p>

        <p>Upon receipt of payment through an online payment service, the client acknowledges that they will refrain from withdrawing or requesting a chargeback without prior notification to ApplyUniNow. This applies regardless of the payment method employed, including all forms except those specifically outlined in the agreement and the procedures governed by law prevailing at the time under the jurisdiction of Hyderabad, State of Telangana.</p>

        <p>Upon receipt of payment through Credit Card or Net Banking, the client voluntarily undertakes to refrain from disputing the payment or notifying the designated bank for a chargeback. They insist that the bank withhold or cancel the payment made to ApplyUniNow. The client further informs their banker that the payment made to ApplyUniNow is genuine and constitutes an exception to their request to cancel or chargeback the payment in their favor. This includes cases of misuse or card loss, either by the client or through an intermediary. The client agrees to cooperate with ApplyUniNow in this matter if ApplyUniNow wishes to defend or represent the matter before any bank or authority.</p>
        <p>The Service Charges imposed by ApplyUniNow are not subject to market rates and are determined in accordance with the company’s established standards, which the client has explicitly consented to. Any subsequent claims, such as excessive charges, will not be entertained. Consequently, the client lacks the right to contest these charges, as they have been clearly communicated and communicated through all available sources of information prior to registration.</p>

        <p>The client acknowledges that immigration requirements may include demonstrating sufficient funds, which vary depending on the country and the immigration pathway or category applied. The client undertakes to fulfill any such requirements as specified by the relevant immigration or other authorities. Failure to provide the required funds by the client will not entitle ApplyUniNow to any refund of service charges or a portion thereof. In such instances, no refund request for service charges will be considered.</p>

        <p>The client acknowledges that any registrations made for any countries prior to the date of this client declaration agreement, if any, with ApplyUniNow will be deemed invalid. Consequently, no claims for the service or fee can be made until a written request is received from ApplyUniNow.
        In case of the Visa approval or permit being rejected on the following grounds there is no refund made: (1.1) if the client fails to attend the interview. (1.2) failure of medicals by the client or his or her family members included in the request. (1.3) if the client does not comply with the requirements of the Embassy or the Consulate. (1.4) failure to provide a genuine Police Clearance Certificate, which is not less than 3 months old. (1.5) failure to prove sufficient funds for settlement by the client or his or her family members. (1.6) prior violation of any immigration law by the client or any of his or her family members. (1.7) late submission of any additional papers requested by the consulate at a later date. (1.8) the client fails to get the required score in English language tests and Adaptive tests to meet the eligibility criteria and as advised by the ApplyUniNow consultant. (1.9) there would be no refund if the client abandons his/her case within two months from the date of registration. (1.10) non-communication with ApplyUniNow’s sonsultant for a period of two months shall also be deemed to be abandonment.</p>

        <p>The fee paid to authorities or any other institution is the client’s liability and is not included in the service charges. ApplyUniNow will not entertain any claim of refund in the event of rejection. This includes university application fees, university non-refundable deposits, or third-party service providers.</p>
        <p>The client will participate in all interviews, as and when required by the relevant agencies, including third-party service providers and institutional partners, at the location specified by the agency. The client will bear the expenses of transportation and accommodation at their own expense. The client will promptly comply with all instructions and orders provided by the agency. Failure to do so will imply that no refund of any secretarial charges offered by ApplyUniNow will be forthcoming.
        It is understood that the submission of a request for immigration is never generic, routine, or time-bound. The concerned case officer may request additional papers, documents, or information, as per the evolving requirements of the procedure, and may request further submission of such additional materials to the relevant immigration authorities. Any request for a refund on these grounds will not be considered.
        The client should also comprehend and accept that no refund or transfer of the ApplyUniNow fee to a friend or relative will be processed in the event that they abandon their request or decide to opt out due to any reason during the proceedings after they have signed up.
        The client will provide all necessary information and documents, including English translations, in the agreed-upon format requested by ApplyUniNow and the relevant office. This arrangement has been finalized by the immigration consultancy based on the client’s provided facts and documents. Should any of the furnished details be found to be inaccurate, fraudulent, incomplete, or incorrect, the offer will not be considered by the concerned immigration authorities. Furthermore, the immigration consultancy assumes no responsibility for any adverse consequences resulting from the petition or the subsequent rejection based on these findings. No refunds will be claimed, either for the consulting fee or the amount paid to government organizations, in such circumstances.</p>
        <p>ApplyUniNow has the right to terminate/withdraw their services without refund of service fee of the client on below terms: (2.1) If the client fails to submit all the necessary papers and documentation within the stipulated time frame, which is typically one month after the date of registration; (2.2) Attempts to defame the company’s name in any manner, which impedes its operational efficiency or damages its reputation; (2.3) Refuses to respond to company emails and phone calls for over a month and subsequently withdraws due to personal circumstances; (2.4) ApplyUniNow reasonably posits that an unauthorized individual is attempting to gain unauthorized access to the Service for their personal gain; (2.5) At the sole discretion of ApplyUniNow, you conduct yourself in a manner that precludes your consultant from continuing to provide the services.
        The client hereby acknowledges its obligation to comply with the requirements of the relevant authorities conducting assessments or determining outcomes. The client also consents to submit all necessary documents, including originals, as requested by the assessing authorities. The client recognizes that any failure to submit these documents or portions thereof constitutes an independent failure on the client’s part. Consequently, ApplyUniNow assumes no responsibility for such failures. Therefore, the client waives any valid claim for a refund based on the inability to produce documents.
        The client will be responsible for paying all outstanding charges to various government agencies and skill assessment organizations, including but not limited to skill assessment costs, residency permit petition fees, acceptable English language or other language tests if applicable, health tests, and so on. The provided or paid charges are non-refundable and cannot be adjusted by either the receiving office or the immigration consultancy, regardless of the final conclusion reached on the petition. A favorable appraisal or conclusion is solely the prerogative of the involved organization, while the immigration consultancy has no control over the final outcome at any stage of the petition. ApplyUniNow has made no guarantees whatsoever of a favorable appraisal or favorable outcome for the client’s projected petition in any phase.
        Upon submitting the petition, the client will notify ApplyUniNow of any significant changes, including: (3.1) housing or mailing address changes; (3.2) educational or specialized credentials; (3.3) change of marital status or service; (3.4) birth of new children; (3.5) any police or unlawful cases – all such notifications must be provided during the petition’s processing and until the issuance of the Permanent Residence Permit. Failure to provide these updates may indicate that no advisory charges have been outstanding.
        The client will appear for an Acceptable English language or other language test, as applicable, and achieve a minimum individual total of the group in each of the four appraisal factors: Listening, Reading, Writing, and Speaking, as appropriate for the client and in accordance with the requirements of the issuing authority or assessment body. The client fully comprehends and agrees that their petition cannot be submitted without the necessary Acceptable English language or other language tests (if applicable), including for partners or dependents over the age of 18. Furthermore, no reimbursement of the advisory, consulting, or secretarial services charge offered to ApplyUniNow will be outstanding or settled in a situation where the client fails to attain the required Acceptable English language or other language test.
        The client shall ensure that they are either married or in a mutually acceptable relationship, such as being the spouse of an acceptable dependent. If applicable, the spouse or acceptable dependent must attend an Acceptable English language or other language test. The client shall submit a report containing the minimum score obtained, as determined by the Service Level Agreement with ApplyUniNow.
        Upon signing and acknowledging the agreement to utilize our services, the client is irrevocably bound to the procedure due to unforeseen personal circumstances that may have arisen. Any attempt to withdraw during the process is unacceptable and will not be entertained. As a business with substantial investment, we are unable to accommodate requests for refunds once services have been rendered or when any portion of the procedure has commenced.
        The client shall diligently disclose to ApplyUniNow, prior to the application process, every detail pertaining to any existing or past instances of wrongdoing, conviction, or insolvency against the client and their dependents. Failure to provide such information, and subsequent discovery of such information, will result in the complete forfeiture of any funds paid to ApplyUniNow.
        ApplyUniNow generates receipts for all payments received; however, it is essential to acknowledge that the company assumes no liability for payments made directly to third parties including employees of ApplyUniNow.
        The client explicitly acknowledges receipt of the customary waiting durations and average timeframes, which are contingent upon the office or appraisal body’s availability. The client fully comprehends that these durations are solely at the discretion of the relevant office or appraisal body. Furthermore, the client understands that they will not have any recourse for a refund of the charge incurred on or off-site due to extended petition timeframes.</p>
        <p>ApplyUniNow has not offered any sort of assurance, advice or pledge on work or job assurance following an approval for the permit and after landing for any given overseas country. No compensation will be claimed of any advisory or consulting or secretarial service charges offered earlier to ApplyUniNow by the client on the ground that ApplyUniNow has been unable to offer a job guarantee abroad.</p>

        <p>In a situation wherein a clash or dispute in the matter of the payment made by a client to ApplyUniNow towards the SERVICE LEVEL AGREEMENT duly inked with ApplyUniNow. The responsibility of ApplyUniNow, in case it arises and is outstanding, either monetary or otherwise, shall not surpass and will be restricted to the charges offered to ApplyUniNow as advisor or consulting or secretarial charges as part of the duly inked SERVICE LEVEL AGREEMENT.
        If your request is under acceptable compliances a refund as subjected to terms and conditions and the service agreement, it’ll take about 30 working days to process.</p>

        <p>The service amount specified is for the full service provided on the date of registration and solely encompasses an individual’s request. Any assumptions of extended services to family members or children are at the client’s sole discretion, and the company will not be held liable for such extensions. The client is obligated to disclose to ApplyUniNow, prior to the expiration of the specified timeframe, all pertinent details, including any existing or past instances of wrongdoing, convictions, or insolvency against themselves or their dependents. Failure to provide such information and subsequent discovery of such information will result in the complete withholding of any refunds paid to ApplyUniNow.</p>

        <p>All fees paid to ApplyUniNow are for the provision of services and assistance, unless otherwise specified. All fees are quoted in Indian Rupees. You are responsible for paying all fees and applicable taxes associated with our services using one of our accepted payment methods.</p>



        <p>Usually, ApplyUniNow clients has meticulously reviewed all the aforementioned provisions, concurs with their validity, and remains steadfast in adhering to all the terms and conditions stipulated in this agreeing terms.</p>

        <p>ApplyUniNow is registered and operated in India, with its registered office located in Hyderabad, Telangana. The laws of the Government of India and the State Government of Telangana will govern the validity, interpretation, and performance of this Agreement. The courts in Hyderabad, Telangana alone shall have jurisdiction to adjudicate any dispute arising out of any issue concerning the company.</p>

        <p>In no event shall the Company be responsible or liable for any failure or delay in the performance of its obligations hereunder arising out of or caused by, directly or indirectly, forces beyond its control. This includes, without limitation, strikes, work stoppages, accidents, acts of war or terrorism, civil or military disturbances, nuclear or natural catastrophes, acts of God, any outbreaks, epidemics, or pandemics; and interruptions, loss, or malfunctions of utilities, communications, or computer (software and hardware) services. It is understood that the Company shall use reasonable efforts to resume service as soon as practicable under the circumstances. Your file will be withheld or deferred until the situation is under control. If we have determined that you are ineligible to apply, no refund will be due on the service fee paid as service has already been initiated.</p>

        <p>Chargeback: The client acknowledges that ApplyUniNow will deploy its employees and utilize additional infrastructure to provide services to the client, incurring substantial financial outlays. Regardless of the outcome of the request, the client hereby commits to refraining from seeking a refund of the fees and charges paid to ApplyUniNow, except as stipulated in the agreed terms. The client further agrees and comprehends the deliverables of the service subscribed to, thereby waiving the right to initiate a chargeback (applicable only to card payments).</p>



        <p>Contact our Officer via email to: support@applyuninow.com</p>
        <p>We will endeavor to respond to you within a reasonable time.</p>


      </div>
    </div>
  )
}

export default RefundPolicy;
