export const data = [
  {
    sno: "01",
    date: "25/04/2022",
    sname: "Navin",
    poc: "Sandeep Verma",
    status: false,
    phone: "+91 9565845685",
    checklist: {
      rating: "12/12",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    sdestination: "UK",
    stage: {
      process: "Pre CAS Process",
      rating: "3/6",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    action: require("./assets/allstudents/view.png"),
  },
  {
    sno: "02",
    date: "25/04/2022",
    sname: "Navin",
    poc: "Sandeep Verma",
    status: false,
    phone: "+91 9565845685",
    checklist: {
      rating: "12/12",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    sdestination: "UK",
    stage: {
      process: "Pre CAS Process",
      rating: "3/6",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    action: require("./assets/allstudents/view.png"),
  },
  {
    sno: "03",
    date: "25/04/2022",
    sname: "Navin",
    poc: "Sandeep Verma",
    status: false,
    phone: "+91 9565845685",
    checklist: {
      rating: "12/12",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    sdestination: "UK",
    stage: {
      process: "Pre CAS Process",
      rating: "3/6",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    action: require("./assets/allstudents/view.png"),
  },
  {
    sno: "04",
    date: "25/04/2022",
    sname: "Navin",
    poc: "Sandeep Verma",
    status: false,
    phone: "+91 9565845685",
    checklist: {
      rating: "12/12",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    sdestination: "UK",
    stage: {
      process: "Pre CAS Process",
      rating: "3/6",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    action: require("./assets/allstudents/view.png"),
  },
  {
    sno: "05",
    date: "25/04/2022",
    sname: "Navin",
    poc: "Sandeep Verma",
    status: false,
    phone: "+91 9565845685",
    checklist: {
      rating: "12/12",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    sdestination: "UK",
    stage: {
      process: "Pre CAS Process",
      rating: "3/6",
      check: require("./assets/allstudents/checked.png"),
      notdone: require("./assets/allstudents/notdone.png"),
    },
    action: require("./assets/allstudents/view.png"),
  },
];
