export const userdata = [
  {
    sno: "01",
    date: "25/04/2022",
    name: "Navin",
    email: "navin@gmail.com",
    makestatus: false,
    phone: "+91 9565845685",
    role: "Agent",
    userstatus: true,
    action: require("./assets/user/edit.png"),
  },
  {
    sno: "02",
    date: "25/04/2022",
    name: "Navin",
    email: "navin@gmail.com",
    makestatus: false,
    phone: "+91 9565845685",
    role: "Agent",
    userstatus: true,
    action: require("./assets/user/edit.png"),
  },
  {
    sno: "03",
    date: "25/04/2022",
    name: "Navin",
    email: "navin@gmail.com",
    makestatus: false,
    phone: "+91 9565845685",
    role: "Agent",
    userstatus: true,
    action: require("./assets/user/edit.png"),
  },
  {
    sno: "04",
    date: "25/04/2022",
    name: "Navin",
    email: "navin@gmail.com",
    makestatus: false,
    phone: "+91 9565845685",
    role: "Agent",
    userstatus: true,
    action: require("./assets/user/edit.png"),
  },
  {
    sno: "05",
    date: "25/04/2022",
    name: "Navin",
    email: "navin@gmail.com",
    makestatus: false,
    phone: "+91 9565845685",
    role: "Agent",
    userstatus: true,
    action: require("./assets/user/edit.png"),
  },
];
